### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by regedarek** [regedarek/kw-app#4]
- [x] worker to remove unpaid reservations after 48hours
- [ ] specs for orders
- [x] multiple reservations per week
- [x] mailing
- [x] zaplac tylko jak wiecej niz zero
- [x] tlumaczenia
- [x] wyglad tabeli
- [ ] dependent destroy and indexes
- [x] obsluga bledow Paymetns::Dotpay::Request

**Comment by regedarek** [comment]
https://robots.thoughtbot.com/referential-integrity-with-foreign-keys

**Comment by regedarek** [comment]
https://github.com/thoughtbot/guides/tree/master/best-practices
